// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ykveh2WfIf2q7EEy16mR4xF0d0mNhvo',
    appId: '1:819964733163:web:d2d7403f6e095eca4f00ae',
    messagingSenderId: '819964733163',
    projectId: 'chitchat-998a7',
    authDomain: 'chitchat-998a7.firebaseapp.com',
    storageBucket: 'chitchat-998a7.firebasestorage.app',
    measurementId: 'G-VSJQ4ZC3ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIE8S7l-Gw8Y-Zv44awrZZZmNhLu_Ofnc',
    appId: '1:819964733163:android:22166936e08217734f00ae',
    messagingSenderId: '819964733163',
    projectId: 'chitchat-998a7',
    storageBucket: 'chitchat-998a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPSeBL4W4SZc4JoKC5kJ1oav8NVwnyx8',
    appId: '1:819964733163:ios:d7c24fbe3261c0d54f00ae',
    messagingSenderId: '819964733163',
    projectId: 'chitchat-998a7',
    storageBucket: 'chitchat-998a7.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZPSeBL4W4SZc4JoKC5kJ1oav8NVwnyx8',
    appId: '1:819964733163:ios:d7c24fbe3261c0d54f00ae',
    messagingSenderId: '819964733163',
    projectId: 'chitchat-998a7',
    storageBucket: 'chitchat-998a7.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ykveh2WfIf2q7EEy16mR4xF0d0mNhvo',
    appId: '1:819964733163:web:6c7dca77795be8944f00ae',
    messagingSenderId: '819964733163',
    projectId: 'chitchat-998a7',
    authDomain: 'chitchat-998a7.firebaseapp.com',
    storageBucket: 'chitchat-998a7.firebasestorage.app',
    measurementId: 'G-B8RWFJG1JH',
  );
}
